### PR TITLE
Feature/check for git repo

### PR DESCRIPTION
**Pull request by hegemanjr**
Check for .git directory in shared folder, suppress destructive actions on provision if it is a git repo. Most users will not notice any change, but users that put their own WordPress repo (git) in the shared folder will notice that it stays the same on provision.

### CODE REVIEW

**Review by miya0001 — APPROVED** [review]

**Comment by Kangomnawe** [comment]
With PCCW, how can we commit folders into my existing git repo?

I already done my local environment with PCCW and need help to share on github for team work.

**Comment by hegemanjr** [comment]
@Kangomnawe What I do for my projects is keep the VCCW environment and WordPress site in two separate repos. My team clones the VCCW environment repo with all the configuration done, then clones the WordPress site repo to the wordpress folder of that environment. Most of the time there are no changes to VCCW; so after the initial setup, my team generally only interacts with the WordPress repo.

**Comment by miya0001** [comment]
@hegemanjr Sorry for delaying. Can we merge this?

**Comment by hegemanjr** [comment]
@miya0001 I thought it had been merged already, so yes.

**Pull request closed without merging**
