### PR TITLE
Multisite subdomain support

### PR DESCRIPTION
**Pull request by yoshida**
Support "subdomain" option in default.yml file. (Related: #98 )

### CODE REVIEW

**Comment by mrgerardorodriguez** [comment]
Yeah, when I tried to figure this out, my issue was I hadn't considered the `hosts` file would also need to be updated once a new subdomain is added. I was unable to find a solution for this.

**Comment by raulillana** [comment]
Sorry to reopen but, can't we relay on the vagrant hostsupdater plugin for that?

**Comment by miya0001** [comment]
Vagrant hosts-updater plugin can add the host entry only during provisioning.
If you add a site on the WordPress dashboard, the sub-domain will not be added.

**Comment by raulillana** [comment]
Mmmm… So a workaround could be to provision (configured to no reset db) after adding them?

**Comment by miya0001** [comment]
Vagrant hosts-updater fires before installing WordPress, so hosts-updater can't get subdomains.

**Comment by youthkee** [comment]
I tried to use subdomains for multisite with VCCW by following way, and it seems to working well.
How about trying same way someone who want to use subdomains, and isn’t it a motivation for adding subdomain support to VCCW?

1. Make aliases for vagrant-host-updater.  
Write an option in `Vagrantfile` like below.

```
config.hostsupdater.aliases = ["multisite.test","sub.multisite.test"]
```

2. Provision the VCCW with multisite setting.  
Write a below option in `site.yml`.

```
multisite: true
```

3. After provisioning, activate subdomain setting of WordPress.  
Change a below option in `wp-config.php`.

```
define( 'SUBDOMAIN_INSTALL', true );
```

4. Then add settings for VirtualHost in guest machine of vagrant.  

```
vagrant ssh
sudo vi /etc/apache2/sites-available/virtual-host.conf
```

Write VirtualHost settings like below.

```
<VirtualHost *:80>
    ServerName multisite.test
    ServerAdmin vccw@example.com
    DocumentRoot  /var/www/html
    ErrorLog /var/log/apache2/multisite.test.error.log
    CustomLog /var/log/apache2/multisite.test.access.log combined
    LogLevel warn
</VirtualHost>

<VirtualHost *:80>
    ServerName sub.multisite.test
    ServerAdmin vccw@example.com
    DocumentRoot  /var/www/html/sub
    ErrorLog /var/log/apache2/sub.multisite.test.error.log
    CustomLog /var/log/apache2/sub.multisite.test.access.log combined
    LogLevel warn
</VirtualHost>
```

Activate settings and restart Apache.

```
sudo a2ensite virtual-host.conf
sudo service apache2 restart
```

5. Login to the admin panel of WordPress, you can add multisites with subdomains now.

My testing environments are below.

Mac OS 10.10.5
VCCW 3.13.0
VirtualBox 5.1.22
Vagrant 1.9.5

**Comment by miya0001** [comment]
@youthkee 

How do you resolve sub-domain?
Are you using Dnsmasq or so?

**Comment by youthkee** [comment]
@miya0001 

I don’t use any other tool else.
I think vagrant-hostsupdater and VirtualHost settings are resolving it.

**Comment by miya0001** [comment]
Ah, I see your solution is adding multi-site statically. 😊

**Comment by miya0001** [comment]
Actually, I am thinking this issue will be solved by using Dnsmasq.
But I don't have enough time to try it. 😓

**Comment by hegemanjr** [comment]
This should be solved with PR #342

**Pull request closed without merging**
