### PR TITLE
fix ERROR! import_playbook is not a valid attribute for a Play

### PR DESCRIPTION
**Pull request by javaongsan**
fix syntax error ERROR! 'import_playbook' is not a valid attribute for a Play

### CODE REVIEW

**Comment by nickohrn** [comment]
@javaongsan Just wanted to say thank you for this. Worked for me.

**Comment by miya0001** [comment]
Thanks @javaongsan 😊 

Hi I can see we should use `include`.
But I don't have problem for now on my environment.
Do you know why?

**Comment by miya0001** [comment]
Related: #310

**Comment by miya0001** [comment]
VCCW is using `ansible_local`, so I expect all users will be using same version of ansible.
I wonder why we are having a problem like this. 😓

**Comment by miya0001** [comment]
Oh, sorry we can't merge this PR.

```
[DEPRECATION WARNING]: 'include' for playbook includes. You should use 
'import_playbook' instead. This feature will be removed in version 2.8. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
```

**Comment by javaongsan** [comment]
Oh, I see. 

"The include action was too confusing, dealing with both plays and tasks, being both dynamic and static. This module will be removed in version 2.8. As alternatives use include_tasks, import_playbook, import_tasks."

My ansible is still at 2.3.2.0.
Thanks!

**Pull request closed without merging**
