### PR TITLE
Update document root

### PR DESCRIPTION
**Pull request by inetbiz**
Changes for issue #301 using vars to build docroot with hostname

### CODE REVIEW

**Comment by inetbiz** [comment]
I'm stuck now because it adds wordpress from synfolder to `/var/www/vhost/{{vccw.hostname}}/public. But, copies wordpress again to a subfolder of the hostname! =(

**Comment by miya0001** [comment]
Hi @inetbiz 😊 

Thanks for PR.
Can you explain more details for this improvements?
We want to know benefits or your use case.

Thanks again.

**Comment by inetbiz** [comment]
Running more than one domain

**Comment by inetbiz** [comment]
Running more than one virtual domain on the instance.

---
From the Desk of Denver Prophit Jr.
Open Source Software Evangelist

[image: Google+] <https://www.google.com/+DenverProphitJr>
<https://www.linkedin.com/in/denverprophit/>
<https://www.linkedin.com/in/denverprophit/>
Tel: +1 321-236-0483 Work
Tel: +1 386-314-3502 Cell

*This message contains confidential information and is intended only for
the individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. E-mail transmission cannot be
guaranteed to be secure or error-free as information could be intercepted,
corrupted, lost, destroyed, arrive late or incomplete, or contain viruses.
The sender therefore does not accept liability for any errors or omissions
in the contents of this message, which arise as a result of e-mail
transmission.* If verification is required please request a hard-copy
version. Denver Prophit Jr., 21204 Newport Sound Pl, New Smyrna Beach, FL,
USA 32168, www.denverprophit.us



On Tue, Jan 2, 2018 at 12:53 PM, Takayuki Miyauchi <notifications@github.com

**Pull request closed without merging**
